-- Vector Golf Performance · Package 7E.4.3 complete VECTOR exercise instructions
-- Adds player-facing movement instructions to the 31 approved VECTOR exercises.
-- No exercise codes or diagnostic links are changed.
update public.library_items as item set
  setup=content.setup,
  instructions=content.instructions,
  intention=content.intention,
  equipment=content.equipment,
  progression=content.progression,
  regression=content.regression,
  pass_criterion=content.pass_criterion,
  updated_at=now()
from (values
('VEC-STR-01','Stand inside the trap bar with feet about hip-width. Hinge and bend the knees to take a centred grip, then brace the trunk with the shoulders set above or slightly ahead of the hands.','1. Push the floor away and stand tall while the bar rises vertically. 2. Finish with hips and knees extended without leaning back. 3. Hinge first, then bend the knees to return the bar under control. 4. Reset your brace before every repetition.','Drive evenly through both feet and move the hips and shoulders upward together.','Trap bar and plates','Add load only while every repetition keeps the same bar path and tempo.','Raise the handles or reduce the load.','All repetitions finish balanced, with an even foot pressure and no visible loss of trunk position.'),
('VEC-STR-02','Hold one dumbbell or kettlebell close to the chest. Stand with feet at a comfortable squat width and toes turned slightly outward.','1. Sit down between the hips while the knees track over the feet. 2. Keep the weight close to the chest and the whole foot connected to the floor. 3. Reach the deepest position you can control. 4. Push the floor away to stand tall.','Keep the torso organised over the middle of the feet and use both legs evenly.','Dumbbell or kettlebell','Increase load, depth or add a controlled pause at the bottom.','Squat to a box or reduce depth and load.','Each repetition reaches a repeatable depth with stable feet, knees and trunk.'),
('VEC-STR-03','Set the bar securely across the upper back, take an even grip and step into a balanced stance with feet at a comfortable squat width.','1. Brace before descending. 2. Bend hips and knees together and lower between the feet. 3. Maintain the bar over the middle of the feet. 4. Push the floor away and stand tall, then reset.','Move the bar vertically while the hips and shoulders rise together.','Rack, barbell and plates','Add load or a brief bottom pause while retaining the same depth and bar path.','Reduce load or squat to a box at a controlled depth.','The chosen depth and bar path remain consistent across the set.'),
('VEC-STR-04','Hold a barbell or dumbbells in front of the thighs. Stand tall with soft knees, feet hip-width and the weights close to the body.','1. Push the hips backward while keeping the weights close to the legs. 2. Lower until the hamstrings are loaded and the trunk remains organised. 3. Press the feet into the floor and drive the hips forward. 4. Finish tall without leaning back.','Create the movement from the hips while maintaining long spine and even foot pressure.','Barbell or dumbbells','Increase load or use a slower lowering phase.','Reduce the range, load or use dowels to rehearse the hinge.','The weights stay close and every repetition finishes through hip extension rather than back extension.'),
('VEC-STR-05','Sit with the upper back supported on a bench and place the load across the hips. Set feet so the shins are approximately vertical at the top.','1. Brace the trunk and drive through the feet. 2. Lift the hips until the body forms a line from shoulders to knees. 3. Pause and squeeze the glutes. 4. Lower the hips under control without changing foot position.','Finish by extending the hips while keeping the ribs and pelvis stacked.','Bench plus barbell, dumbbell or band','Increase load, add a top pause or progress to a single-leg variation.','Use bodyweight, a band or a shorter range.','The top position is repeatable without the ribs flaring or the lower back taking over.'),
('VEC-STR-06','Lie on the bench with eyes under the bar, feet planted and shoulder blades gently set. Take an even grip and position the wrists above the elbows.','1. Unrack and hold the bar over the shoulders. 2. Lower toward the lower chest with forearms controlled. 3. Press upward and slightly back to the start. 4. Reset the shoulder position before the next repetition.','Press from a stable base and keep the bar, wrists and elbows organised.','Bench and barbell or dumbbells','Increase load or add a controlled pause just above the chest.','Use dumbbells, reduce load or shorten the range with a block.','The bar follows a repeatable path and both arms finish together.'),
('VEC-STR-07','Stand in a split or square stance facing the landmine. Hold the bar end at shoulder height with the working hand and keep the trunk tall.','1. Press the bar upward and forward along its natural arc. 2. Allow the shoulder blade to move around the ribcage. 3. Finish with the arm long and ribs controlled. 4. Lower to the shoulder under control.','Transfer force from the floor through a stable trunk into the pressing arm.','Landmine and barbell','Use a half-kneeling stance, add load or include a controlled step.','Use two hands or reduce the load and range.','The hand follows the bar arc without trunk sway or unwanted rotation.'),
('VEC-STR-08','Set the cable or support a free hand on a bench. Begin with the working arm long, shoulder relaxed and trunk held still.','1. Pull the elbow toward the back pocket. 2. Let the shoulder blade move back without twisting the torso. 3. Pause briefly with the hand beside the ribs. 4. Return until the arm is long again.','Move the shoulder blade and arm together while the trunk remains quiet.','Cable or dumbbell and bench if required','Increase load, add a pause or progress to an unsupported stance.','Reduce load or use chest support.','The elbow completes the same path without the torso rotating or shrugging.'),
('VEC-STR-09','Stand between two equal weights, hinge to grip them and stand tall with arms long at the sides.','1. Set the ribs over the pelvis and look ahead. 2. Walk with short, deliberate steps. 3. Keep the weights quiet and the body tall. 4. Turn carefully or place the weights down, then reset.','Carry a strong posture while producing an even, rhythmic gait.','Matched dumbbells or kettlebells and a measured route','Increase load or distance, or progress to a one-sided suitcase carry.','Reduce load or distance and use shorter sets.','Posture, step rhythm and weight position remain unchanged for the full distance.'),
('VEC-PWR-01','Stand tall with feet about hip-width and arms relaxed. Choose a clear landing space and begin each repetition from a complete reset.','1. Dip quickly by bending hips and knees. 2. Reverse direction immediately and jump vertically with full intent. 3. Land softly through the whole foot. 4. Stand, reset and repeat only when ready.','Move down quickly, reverse forcefully and project the body straight upward.','Open floor; jump mat optional','Add an arm swing, measure jump height or use a very light external load.','Use a smaller jump or rapid calf raise with the same quick reversal.','Each jump is explosive and lands in balance within the original footprint.'),
('VEC-PWR-02','Stand behind a start line with feet about hip-width and a clear landing area ahead.','1. Swing the arms back while dipping through hips and knees. 2. Drive forward and extend the hips, knees and ankles. 3. Reach the feet forward for landing. 4. Absorb the landing and hold it before standing.','Project the body forward powerfully, then own the landing.','Floor line and measuring tape optional','Measure distance or use repeated bounds only after single landings are consistent.','Reduce jump distance or use a two-foot hop and stick.','The landing is held for two seconds without an extra step.'),
('VEC-PWR-03','Stand side-on to a solid wall with a medicine ball held near the trail hip. Use an athletic stance and leave enough distance for the ball to rebound safely.','1. Load into the leg away from the wall. 2. Drive from the ground and rotate the hips and trunk toward the wall. 3. Throw the ball hard at chest height. 4. Catch or retrieve it, reset fully and repeat.','Sequence force from the ground through the pelvis and trunk into the throw.','Medicine ball and solid wall','Use a slightly heavier ball only if release speed stays high, or add a small step.','Use a lighter ball or kneeling position to reduce lower-body demand.','The ball leaves fast on the intended line while the finish remains balanced.'),
('VEC-PWR-04','Stand side-on to the wall holding a medicine ball, with enough space to make one controlled step toward the target.','1. Step toward the wall with the lead foot. 2. Let the step load the lower body and begin the rotation. 3. Drive through the ground and throw from the hip or chest. 4. Finish over the lead leg, retrieve and reset.','Blend linear momentum into rotation without rushing the throwing action.','Medicine ball and solid wall','Increase approach speed slightly or use a shuffle before the throw.','Return to a static rotational throw.','The step, rotation and release occur in sequence and the finish is stable.'),
('VEC-PWR-05','Stand side-on with the ball held low near the hip away from the throwing direction. Use a clear open throwing area or solid wall.','1. Shift into the trail hip and lower the ball slightly. 2. Drive the floor away and rotate toward the target. 3. Scoop the ball across and release on a powerful horizontal arc. 4. Finish tall and balanced before resetting.','Project the ball through coordinated leg drive and fast rotation.','Medicine ball with wall or open throwing area','Add a step or use a slightly heavier ball while preserving speed.','Use a lighter ball and a smaller range of rotation.','Release speed stays high and the ball travels on the intended horizontal line.'),
('VEC-PWR-06','Stand on one leg with the other foot just off the floor and clear space to the side.','1. Dip into the standing hip. 2. Push sideways and jump onto the opposite foot. 3. Absorb the landing through ankle, knee and hip. 4. Hold the position before resetting in the other direction.','Produce lateral force, then stop it under control on one leg.','Open floor and landing markers optional','Increase distance or link consecutive bounds once each landing is owned.','Reduce distance or step laterally and hold the single-leg position.','Every landing is held for two seconds with knee, pelvis and trunk controlled.'),
('VEC-SPD-01','Warm up, then stand at a normal driver setup with radar positioned to capture speed. Use a clear swing area and no ball.','1. Make one rehearsal at moderate speed. 2. Make three swings at maximum controllable intent with full finish. 3. Read and record each speed. 4. Rest fully before the next set.','Swing the clubhead as fast as possible without protecting the finish or steering an imaginary ball.','Driver and swing-speed radar','Try to raise the best or average set speed while retaining control.','Use three-quarter intent or fewer swings per set.','Speed remains near the session best and every swing finishes in balance.'),
('VEC-SPD-02','Set up normally with a purpose-designed light speed implement and radar. Begin after a progressive warm-up.','1. Make one familiarisation swing. 2. Swing the light implement as fast as possible through the hitting area. 3. Complete the finish rather than braking the motion. 4. Record speed and rest fully between sets.','Experience a faster movement rate and allow the body to organise around speed.','Purpose-designed light speed implement and radar','Increase intent or alternate light and normal implements.','Reduce swing length or speed intent.','The implement accelerates freely and the finish remains coordinated across all repetitions.'),
('VEC-SPD-03','Take a normal golf stance with a purpose-designed heavy speed implement after completing lighter warm-up swings.','1. Make one controlled rehearsal. 2. Swing with high intent while keeping the motion continuous. 3. Complete the turn and balanced finish. 4. Rest before repeating; avoid grinding slow repetitions.','Apply force through the full swing while still moving the implement with speed.','Purpose-designed heavy speed implement','Contrast immediately with a normal or light implement.','Use a lighter implement or reduce the number of repetitions.','Each swing remains dynamic and coordinated rather than becoming a slow strength effort.'),
('VEC-SPD-04','Return to the normal driver after the light/heavy contrast work. Set the radar in the same position used for the baseline.','1. Make one settling rehearsal. 2. Swing the driver at maximum controllable intent. 3. Record all three speeds. 4. Compare the best and average with the opening baseline.','Let the normal club feel fast and transfer the preceding speed exposure without forcing.','Driver and swing-speed radar','Repeat the contrast only if the normal-club speed responds positively.','Take additional rest or return to submaximal normal-club swings.','Normal-club speed equals or exceeds baseline with a balanced finish.'),
('VEC-SPD-05','Tee a ball for driver, mark the face for strike feedback and set the launch monitor or radar. Choose a broad target corridor.','1. Hit one controlled baseline shot. 2. Increase intent while keeping the same setup and target. 3. Record club speed, ball speed, strike and whether the ball finishes in the corridor. 4. Reset fully for every ball.','Turn available swing speed into centred contact and useful ball speed.','Driver, balls, tees, face spray and launch monitor','Narrow the target corridor or raise the required ball-speed threshold.','Reduce intent and widen the target corridor.','The set retains acceptable strike and target outcome while ball speed rises above baseline.'),
('VEC-SPD-06','Create a defined target corridor and use a driver, balls and speed measurement. Establish the minimum speed and accuracy standards before starting.','1. Predict the intended shot. 2. Swing with high intent and record speed. 3. Mark whether the ball starts and finishes inside the corridor. 4. Rest, reset and repeat until the set is complete.','Produce speed for a golf task rather than speed without consequence.','Driver, balls, target corridor and radar or launch monitor','Narrow the corridor, vary the target or use a scored competitive set.','Widen the corridor or reduce the speed requirement.','Meet both the agreed speed threshold and target standard for the required number of shots.'),
('VEC-CON-01','Choose a level route or treadmill and begin at an easy walking pace with relaxed posture.','1. Walk continuously at a pace that allows comfortable conversation. 2. Keep the stride natural and arms relaxed. 3. Maintain the same effort rather than chasing distance. 4. Finish with several easy minutes.','Accumulate steady aerobic work while remaining fresh enough for golf and strength practice.','Walking route, treadmill and timer','Extend duration gradually or include gentle inclines.','Shorten duration or divide the walk into two bouts.','The full duration is completed at a steady conversational effort.'),
('VEC-CON-02','Adjust the bike so the knees retain a slight bend at the bottom of the pedal stroke. Begin with light resistance.','1. Pedal easily for several minutes. 2. Settle into a smooth cadence and conversational effort. 3. Keep the upper body relaxed while maintaining continuous pressure. 4. Reduce resistance for the final minutes.','Build steady aerobic work with smooth, economical pedalling.','Stationary or outdoor bike and timer','Extend duration or add modest resistance while retaining the same effort.','Shorten the ride or lower resistance.','The full duration is completed with stable cadence and conversational breathing.'),
('VEC-CON-03','Choose a bike, treadmill or measured route. Warm up easily and set a timer for work and recovery periods.','1. Raise the pace for three minutes to a controlled strong effort. 2. Reduce to easy movement for ninety seconds. 3. Repeat for the prescribed intervals. 4. Keep the final interval as controlled as the first, then cool down.','Repeat strong aerobic efforts without turning them into sprints.','Bike, treadmill or measured route and interval timer','Add one interval or slightly raise the work pace.','Complete fewer intervals or lengthen the easy recovery.','All work intervals are completed at a similar pace without a marked final-interval drop.'),
('VEC-CON-04','Set a walking route and a nearby clear area for golf swings. Keep a club ready so the changeover is immediate.','1. Walk briskly for eight minutes. 2. Move directly to the swing area. 3. Make four purposeful swings to a defined target or movement standard. 4. Record swing quality, then begin the next walking cycle.','Retain organised golf movement and decision quality after a manageable walking load.','Walking space, golf club, balls or swing area and timer','Increase walking pace slightly or add a target consequence to the swings.','Shorten the walk or use rehearsals without a ball.','The final cycle meets the same swing-quality standard as the first.'),
('VEC-UNI-01','Take a split stance with feet on separate rails, front foot flat and rear heel raised. Hold weights at the sides if used.','1. Lower straight down by bending both knees. 2. Keep most pressure through the front whole foot. 3. Stop at the controlled depth. 4. Push through the front leg to return to the start.','Let the front leg produce the work while the pelvis and trunk remain organised.','Dumbbells optional','Add load, depth or elevate the rear foot.','Use bodyweight, reduce depth or hold a support.','Both sides complete the same controlled range without loss of balance.'),
('VEC-UNI-02','Stand facing a stable box with the whole working foot placed on top. Hold weights at the sides if required.','1. Shift pressure onto the foot on the box. 2. Push through that leg to rise without springing from the floor foot. 3. Stand tall on the box. 4. Lower under control and reset.','Create the rise from the working leg while keeping the pelvis level.','Stable box and dumbbells optional','Increase box height or load while keeping the same control.','Lower the box or use hand support.','Each repetition is driven by the box leg and finishes without loss of balance.'),
('VEC-UNI-03','Stand on one leg with a soft knee, holding a dumbbell in the opposite or same hand. Use light fingertip support if needed.','1. Reach the free leg backward as the hips hinge. 2. Keep the pelvis facing the floor and the weight close to the standing leg. 3. Stop at the deepest controlled position. 4. Drive the standing foot down and bring the hips forward.','Load the standing hip while maintaining balance and a square pelvis.','Dumbbell optional and light support','Increase load or remove hand support.','Use hand support, reduce range or perform a kickstand hinge.','The pelvis stays controlled and the standing foot remains stable throughout.'),
('VEC-UNI-04','Stand balanced on one leg in a clear landing area. Begin every repetition from a complete reset.','1. Dip quickly through the standing hip, knee and ankle. 2. Jump vertically with full intent. 3. Land on the same foot and absorb the force. 4. Hold the landing before resetting.','Produce force rapidly from one leg, then regain control on the same side.','Open floor; jump mat optional','Measure height or add a small forward or lateral direction.','Use a smaller hop or assisted take-off.','Each landing is held for two seconds without the free foot touching down.'),
('VEC-UNI-05','Stand square to a cable with the handle in one hand and the arm long. Set the ribs over the pelvis and keep both feet grounded.','1. Pull the elbow toward the back pocket. 2. Allow the shoulder blade to move without turning the torso. 3. Pause with the hand beside the ribs. 4. Return the arm to full length under control.','Create unilateral pulling force while resisting unwanted trunk rotation.','Cable and single handle','Use a split stance, increase load or perform half-kneeling.','Reduce load or use the free hand for light support.','The torso remains square while the working shoulder completes a full repeatable path.'),
('VEC-UNI-06','Face the landmine in a split or half-kneeling stance and hold the bar end at the working shoulder.','1. Set the trunk and press the bar upward and forward. 2. Allow the shoulder blade to rotate naturally. 3. Finish with the arm long and body centred. 4. Lower the bar to the shoulder and reset.','Press through one arm while the lower body and trunk provide a stable force platform.','Landmine and barbell','Progress from half-kneeling to standing or add a controlled step.','Reduce load or use both hands.','The bar follows a smooth arc while the trunk stays centred and controlled.')
) as content(code,setup,instructions,intention,equipment,progression,regression,pass_criterion)
where item.code=content.code and item.item_type='vector_exercise';

do $$
declare total integer; ready integer;
begin
  select count(*),count(*) filter(where instruction_complete) into total,ready
  from public.library_items
  where item_type='vector_exercise' and code like 'VEC-%';
  if total<>31 then raise exception 'Expected 31 VECTOR exercises, found %',total; end if;
  if ready<>31 then raise exception 'Expected 31 player-ready VECTOR exercises, found %',ready; end if;
end $$;

