-- Package 7E.1 · diagnostic entry gates; these are hypotheses and tests, never automatic body diagnoses
insert into public.diagnostic_rules(code,title,fault_family,observation,evidence_required,minimum_opportunities,confidence_rule,guardrail,status) values
('DX-PATH-R','Rightward path family','FF-PATH-R','Measured club path is farther right than required for the intended flight.','Representative matched sample with target, intention, strike, face and path recorded.',5,'Raise confidence only when the pattern persists and a controlled comparison changes path as predicted.','Do not infer grip, backswing, pelvis or another movement cause from path alone.','approved'),
('DX-PATH-L','Leftward path family','FF-PATH-L','Measured club path is farther left than required for the intended flight.','Representative matched sample with target, intention, strike, face and path recorded.',5,'Raise confidence only when the pattern persists and a controlled comparison changes path as predicted.','Do not infer a body-movement cause from path alone.','approved'),
('DX-PATH-V','Variable path family','FF-VARIABLE','Ordered path data shows excessive spread, clusters or sign changes.','Shot-order sample preserving target, club, intention, strike, face and path.',8,'Confidence rises when a candidate variable travels with the changing path and its test narrows the distribution.','Do not average opposing patterns into a neutral mean.','approved'),
('DX-FACE-R','Rightward face family','FF-FACE-R','Face angle is farther right than required for intended start and curve.','Matched face, launch, path and centred-strike sample.',5,'Retain only when a controlled test produces the predicted face response without unacceptable path or strike cost.','Start direction alone does not prove the cause.','approved'),
('DX-FACE-L','Leftward face family','FF-FACE-L','Face angle is farther left than required for intended start and curve.','Matched face, launch, path and centred-strike sample.',5,'Retain only when a controlled test produces the predicted face response without unacceptable path or strike cost.','Do not diagnose release pattern from curve alone.','approved'),
('DX-FACE-V','Variable face family','FF-FACE-VARIABLE','Ordered face data shows excessive spread, clusters or sign changes.','Shot-order sample preserving aim, intention, strike, face and path.',8,'Confidence rises when the tested variable narrows the face distribution and the result survives a no-aid retest.','Do not average left and right face delivery into a stable condition.','approved'),
('DX-LOWPOINT','Low-point/contact family','FF-LOWPOINT','Face strike or ground contact is outside the intended zone or excessively variable.','Marked strike and ground-contact sample in shot order with task and lie controlled.',5,'Retain only when the predicted contact feature changes and flight, face, path, speed and pain remain acceptable.','Do not infer a movement fault before the strike task and intention are understood.','approved')
on conflict (code) do update set title=excluded.title,fault_family=excluded.fault_family,observation=excluded.observation,evidence_required=excluded.evidence_required,minimum_opportunities=excluded.minimum_opportunities,confidence_rule=excluded.confidence_rule,guardrail=excluded.guardrail,status=excluded.status;
