"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { AppShell } from "../../ui/app-shell";
import { getSupabaseBrowserClient } from "../../../lib/supabase/client";
import { queueRound,syncQueuedRounds } from "../../../lib/offline-sync";
import { CourseMap } from "../../../src/components/course/CourseMap";
import { distanceYards,lieForPoint,traditionalMetrics,vectorBands,type Coordinate,type CourseFeature,type CourseHole,type MappedShot } from "../../../lib/course-mapping";

type Course={id:string;name:string;provider_course_id:string};
const clubs=["Driver","3 wood","5 wood","Hybrid","4 iron","5 iron","6 iron","7 iron","8 iron","9 iron","Pitching wedge","Gap wedge","Sand wedge","Lob wedge","Putter"];

export default function MappingRound(){
  const[courses,setCourses]=useState<Course[]>([]),[courseId,setCourseId]=useState(""),[holes,setHoles]=useState<CourseHole[]>([]),[features,setFeatures]=useState<CourseFeature[]>([]),[holeNumber,setHoleNumber]=useState(1),[shots,setShots]=useState<MappedShot[]>([]),[club,setClub]=useState("Driver"),[success,setSuccess]=useState(true),[penalty,setPenalty]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{const sb=getSupabaseBrowserClient();if(!sb)return;void sb.from("course_catalog").select("id,name,provider_course_id").order("name").then(({data})=>{const rows=(data||[])as Course[];setCourses(rows);setCourseId(current=>current||rows[0]?.id||"")})},[]);
  const loadCourse=useCallback(async()=>{const sb=getSupabaseBrowserClient();if(!sb||!courseId)return;const[holeResult,featureResult]=await Promise.all([sb.from("course_holes").select("id,hole_number,par,yardage,tee_latitude,tee_longitude,green_front_latitude,green_front_longitude,green_center_latitude,green_center_longitude,green_back_latitude,green_back_longitude").eq("course_id",courseId).order("hole_number"),sb.from("course_features").select("id,hole_id,feature_type,geometry").eq("course_id",courseId)]);setHoles((holeResult.data||[])as CourseHole[]);setFeatures((featureResult.data||[]).map(row=>({...row,geometry:row.geometry as Coordinate[]}))as CourseFeature[])},[courseId]);
  useEffect(()=>{void loadCourse()},[loadCourse]);
  useEffect(()=>{const saved=localStorage.getItem("vgp-mapping-draft");if(saved)try{setShots(JSON.parse(saved))}catch{}},[]);
  useEffect(()=>{localStorage.setItem("vgp-mapping-draft",JSON.stringify(shots))},[shots]);
  const hole=holes.find(item=>item.hole_number===holeNumber),holeFeatures=features.filter(feature=>feature.hole_id===hole?.id),holeShots=shots.filter(shot=>shot.holeNumber===holeNumber);
  const green=hole?.green_center_latitude!=null&&hole.green_center_longitude!=null?{latitude:hole.green_center_latitude,longitude:hole.green_center_longitude}:null;
  const addShot=(end:Coordinate)=>{if(!hole||!green)return;const prior=holeShots.at(-1);const start=prior?{latitude:prior.endLatitude,longitude:prior.endLongitude}:hole.tee_latitude!=null&&hole.tee_longitude!=null?{latitude:hole.tee_latitude,longitude:hole.tee_longitude}:null;if(!start){setMessage("This hole needs a tee coordinate before shots can be mapped.");return}const endLie=lieForPoint(end,holeFeatures);setShots(all=>[...all,{id:crypto.randomUUID(),courseHoleId:hole.id,holeNumber,sequence:holeShots.length+1,club,startLatitude:start.latitude,startLongitude:start.longitude,endLatitude:end.latitude,endLongitude:end.longitude,startLie:prior?.endLie||"tee",endLie,distanceYards:Math.round(distanceYards(start,end)*10)/10,distanceToGreenYards:Math.round(distanceYards(end,green)*10)/10,success,penalty}]);setPenalty(false);setClub(endLie==="green"?"Putter":club)};
  const metrics=useMemo(()=>traditionalMetrics(shots,holes),[shots,holes]);
  const undo=()=>setShots(all=>{const index=all.map((shot,i)=>shot.holeNumber===holeNumber?i:-1).filter(i=>i>=0).at(-1);return index===undefined?all:all.filter((_,i)=>i!==index)});
  const save=async()=>{const course=courses.find(item=>item.id===courseId);if(!course||!shots.length)return;const id=crypto.randomUUID();await queueRound({id,recordedAt:new Date().toISOString(),courseId,courseName:course.name,entryMode:"mapping",bands:vectorBands(shots),mappedShots:shots});const result=await syncQueuedRounds();setMessage(result.synced?"Mapped round securely synced.":"Round saved on this device and queued to sync.");if(result.synced){setShots([]);localStorage.removeItem("vgp-mapping-draft")}};
  return <AppShell active="rounds"><header className="map-heading"><div><p className="eyebrow">GPS shot mapping</p><h1>{courses.find(item=>item.id===courseId)?.name||"Course mapping"}</h1></div><div className="map-course-select"><label>Course<select value={courseId} onChange={event=>setCourseId(event.target.value)}>{courses.map(course=><option value={course.id} key={course.id}>{course.name}</option>)}</select></label><span>{shots.length} shots</span></div></header>
  {message&&<div className="success-banner" role="status">{message}</div>}
  {!courses.length?<section className="map-onboarding"><span>04</span><h2>Ready for the Stracka test course.</h2><p>The mapping engine is installed. Import Copt Heath from the coach-only course importer once the Golf Intelligence test token is available.</p></section>:<><nav className="map-hole-picker" aria-label="Choose hole">{holes.map(item=><button key={item.id} className={item.hole_number===holeNumber?"active":""} onClick={()=>setHoleNumber(item.hole_number)}><span>{item.hole_number}</span><small>Par {item.par||"—"}</small></button>)}</nav>{hole&&<div className="mapping-layout"><section><CourseMap hole={hole} features={holeFeatures} shots={holeShots} onSelect={addShot}/></section><aside className="shot-control"><p className="eyebrow">Hole {hole.hole_number} · Par {hole.par||"—"}</p><div className="green-distance"><strong>{holeShots.at(-1)?.distanceToGreenYards??hole.yardage??"—"}</strong><span>yards to centre</span></div><label>Club<select value={club} onChange={event=>setClub(event.target.value)}>{clubs.map(item=><option key={item}>{item}</option>)}</select></label><fieldset><legend>Was the shot successful?</legend><button className={success?"active":""} onClick={()=>setSuccess(true)}>Yes</button><button className={!success?"active miss":""} onClick={()=>setSuccess(false)}>No</button></fieldset><label className="penalty-check"><input type="checkbox" checked={penalty} onChange={event=>setPenalty(event.target.checked)}/>Penalty shot</label><button className="undo-action" disabled={!holeShots.length} onClick={undo}>Undo last shot</button><div className="shot-log">{holeShots.map(shot=><div key={shot.id}><b>{shot.sequence}</b><span>{shot.club}<small>{shot.distanceYards} yd · {shot.endLie.replaceAll("_"," ")}</small></span><i>{shot.success?"✓":"×"}</i></div>)}</div></aside></div>}<section className="live-metrics"><div><strong>{metrics.fairwaysHit}/{metrics.fairwayOpportunities}</strong><span>Fairways</span></div><div><strong>{metrics.greensInRegulation}</strong><span>GIR</span></div><div><strong>{metrics.putts}</strong><span>Putts</span></div><div><strong>{metrics.averageDrive??"—"}</strong><span>Avg drive</span></div><div><strong>{metrics.successRate??"—"}%</strong><span>Vector success</span></div></section><footer className="map-footer"><p>Draft saved automatically on this device.</p><button className="primary-action" disabled={!shots.length} onClick={save}>Finish and save round</button></footer></>}
  </AppShell>;
}
