"use client";
import { AppShell } from "./ui/app-shell";
import { MetricCard } from "./ui/metric-card";
import { usePlayerData } from "../lib/use-player-data";

export default function Home() {
  const { profile, rounds, aggregates, loading } = usePlayerData();
  const totalOpp = aggregates.reduce((s, r) => s + r.opportunities, 0); const totalSuccess = aggregates.reduce((s, r) => s + r.successes, 0);
  const performance = totalOpp ? Math.round(totalSuccess / totalOpp * 100) : 0; const confidence = Math.min(100, Math.round(totalOpp / 1.2));
  const priorities = aggregates.map((r) => { const rate = r.opportunities ? r.successes / r.opportunities : 0; const frequency = totalOpp ? r.opportunities / totalOpp : 0; const evidence = Math.min(1, r.opportunities / 5); return { ...r, rate, frequency, score: frequency * (1-rate) * evidence }; }).sort((a,b) => b.score-a.score);
  const firstName = profile?.display_name?.split(" ")[0] || "player"; const top = priorities[0];
  return <AppShell active="today"><section className="hero-panel"><div><p className="eyebrow">Your live performance engine</p><h1>{loading ? "Loading your game…" : `Welcome back, ${firstName}.`}</h1><p className="hero-copy">{top ? `Your highest-value practice opportunity is ${top.shot_band}, based on both performance and how often you face the shot.` : "Record a round to create your first evidence-led practice priority."}</p></div><a className="primary-action" href="/rounds">Choose round entry <span aria-hidden="true">→</span></a></section>
    <section className="metric-grid" aria-label="Performance overview"><MetricCard label="Success rate" value={`${performance}%`} detail={`${totalSuccess} successful from ${totalOpp} opportunities`} accent="green"/><MetricCard label="Rounds recorded" value={`${rounds.length}`} detail={rounds[0] ? `Latest ${new Date(rounds[0].played_at).toLocaleDateString("en-GB")}` : "Add your first round"} accent="blue"/><MetricCard label="Data confidence" value={`${confidence}%`} detail={confidence >= 80 ? "Reliable practice signal" : "Builds with every recorded opportunity"} accent="amber"/></section>
    <div className="content-grid"><section className="panel priority-panel"><div className="section-heading"><div><p className="eyebrow">Engine priority</p><h2>Where gains are waiting</h2></div><a href="/performance">Full analysis</a></div><div className="priority-list">{priorities.slice(0,3).map((area,index) => <article className="priority-row" key={area.shot_band}><span className="rank">0{index+1}</span><div className="priority-copy"><strong>{area.shot_band}</strong><span>{Math.round(area.frequency*100)}% of opportunities · {Math.round(area.rate*100)}% successful</span></div><div className={`score-ring ${index===0?"amber":index===1?"green":"blue"}`}><strong>{Math.round(area.score*100)}</strong><span>priority</span></div></article>)}{!priorities.length && <p className="empty-copy">No priorities yet. Your first saved round will start the engine.</p>}</div></section>
    <aside className="panel practice-panel"><div className="section-heading"><div><p className="eyebrow">Next session</p><h2>{top ? top.shot_band : "Awaiting round data"}</h2></div><span className="duration">30 min</span></div><div className="practice-block"><span>01</span><div><strong>Calibrate</strong><p>Define your success standard</p></div><b>8 min</b></div><div className="practice-block"><span>02</span><div><strong>Random challenge</strong><p>Change target and context each ball</p></div><b>14 min</b></div><div className="practice-block"><span>03</span><div><strong>Vector movement</strong><p>Movement support selected in Package 7E</p></div><b>8 min</b></div></aside></div>
    <section className="insight-strip"><div className="insight-mark">V</div><div><p className="eyebrow">What the engine considers</p><h2>Failure alone does not set the priority.</h2><p>Each score blends success rate, frequency of the shot and evidence volume, preventing one rare bunker failure from dominating your practice plan.</p></div><a href="/performance">See calculations <span>→</span></a></section></AppShell>;
}
