import type { BandAggregate } from "./use-player-data";

export type MissAggregate = { shot_band: string; failures: number; short: number; long: number; left: number; right: number };
export type EvidenceConfidence = "insufficient" | "emerging" | "moderate" | "strong";
export type DiagnosticObservation = { band:string; opportunities:number; successes:number; failureRate:number; frequency:number; priorityScore:number; confidence:EvidenceConfidence; confidenceScore:number; pattern:string; patternKey:"short"|"long"|"left"|"right"|"mixed"|"unrecorded"; evidenceSummary:string; interpretation:string; nextTest:string; guardrail:string; suggestedCodes:string[] };

const drillFamily:Record<string,string>={"Tee shot":"3A","Over 200 yd":"3C","150–200 yd":"4A","125–150 yd":"4A","100–125 yd":"4A","50–100 yd":"4B","Under 50 yd":"4B",Bunker:"4C","Putting 0–6 ft":"5","Putting 6 ft+":"5"};
function confidenceFor(opportunities:number,failuresWithDirection:number,failures:number):{label:EvidenceConfidence;score:number}{if(opportunities<5)return{label:"insufficient",score:Math.round(opportunities/5*35)};const coverage=failures?failuresWithDirection/failures:0;if(opportunities>=20&&coverage>=.7)return{label:"strong",score:90};if(opportunities>=10&&coverage>=.5)return{label:"moderate",score:70};return{label:"emerging",score:50}}
export function buildDiagnosticObservations(bands:BandAggregate[],misses:MissAggregate[]):DiagnosticObservation[]{const total=bands.reduce((sum,row)=>sum+row.opportunities,0);return bands.filter(row=>row.opportunities>0).map((row):DiagnosticObservation=>{const miss=misses.find(item=>item.shot_band===row.shot_band)||{shot_band:row.shot_band,failures:row.opportunities-row.successes,short:0,long:0,left:0,right:0};const failures=Math.max(row.opportunities-row.successes,miss.failures);const counts=[{key:"short" as const,value:miss.short},{key:"long" as const,value:miss.long},{key:"left" as const,value:miss.left},{key:"right" as const,value:miss.right}].sort((a,b)=>b.value-a.value);const dominant=counts[0],second=counts[1];const patternKey:DiagnosticObservation["patternKey"]=dominant.value===0?"unrecorded":dominant.value===second.value?"mixed":dominant.key;const described=patternKey==="unrecorded"?"No directional pattern recorded":patternKey==="mixed"?"Mixed miss pattern":`${patternKey[0].toUpperCase()}${patternKey.slice(1)} is the leading recorded miss`;const confidence=confidenceFor(row.opportunities,miss.left+miss.right,failures);const frequency=total?row.opportunities/total:0,failureRate=failures/row.opportunities,priorityScore=frequency*failureRate*Math.min(1,row.opportunities/5);const family=drillFamily[row.shot_band]||"3C";const codes=[`DR-${family}-01`,`DR-${family}-02`,`DR-${family}-26`];if(["Tee shot","Over 200 yd","150–200 yd","125–150 yd","100–125 yd"].includes(row.shot_band))codes.push("VEC-PWR-03");else if(row.shot_band.includes("Putting"))codes.push("VEC-UNI-05");else codes.push("VEC-UNI-01");return{band:row.shot_band,opportunities:row.opportunities,successes:row.successes,failureRate,frequency,priorityScore,confidence:confidence.label,confidenceScore:confidence.score,pattern:described,patternKey,evidenceSummary:`${row.successes}/${row.opportunities} successful · ${Math.round(frequency*100)}% of recorded opportunities · ${failures} failures`,interpretation:patternKey==="unrecorded"?"The scoring weakness is visible, but there is not yet enough miss information to propose a directional hypothesis.":`This is an observation of the ${patternKey} result pattern, not a diagnosis of its swing or physical cause.`,nextTest:patternKey==="unrecorded"?"Record short/long and left/right for the next five failures in this band.":`Use a controlled baseline and comparison set to test whether the ${patternKey} pattern repeats with intention, target and strike held constant.`,guardrail:"Do not infer a body movement fault from on-course outcome data alone. The coach must verify the pattern before approving a prescription.",suggestedCodes:codes}}).sort((a,b)=>b.priorityScore-a.priorityScore)}
