import{getSupabaseBrowserClient}from"./supabase/client";
export type DetailedShot={id:string;holeNumber:number;sequence:number;shotBand:string;success:boolean;missLength:"short"|"long"|null;missDirection:"left"|"right"|null};export type QueuedRound={id:string;recordedAt:string;courseName?:string;entryMode?:"quick"|"detailed";bands:Array<{id:string;label:string;opportunities:number|null;successes:number|null}>;detailedShots?:DetailedShot[]};
export type QueueRecord={id:string;kind:"round";payload:QueuedRound;status:"pending"|"failed";attempts:number;created_at:string;updated_at:string;next_attempt_at:string|null;last_error:string|null;user_id:string|null};
const DB="vector-golf-sync",STORE="operations",LEGACY="vgp-round-queue",EVENT="vgp-sync-change";let syncing=false;let pendingWrites=Promise.resolve();
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:"id"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function changed(){if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent(EVENT))}
async function put(record:QueueRecord){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(record);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close();changed()}
async function remove(id:string){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close();changed()}
export async function readQueue():Promise<QueueRecord[]>{if(typeof window==="undefined"||!("indexedDB"in window))return[];const db=await openDb();const result=await new Promise<QueueRecord[]>((resolve,reject)=>{const tx=db.transaction(STORE,"readonly");const request=tx.objectStore(STORE).getAll();request.onsuccess=()=>resolve(request.result as QueueRecord[]);request.onerror=()=>reject(request.error)});db.close();return result.sort((a,b)=>a.created_at.localeCompare(b.created_at))}
export async function migrateLegacyQueue(){if(typeof window==="undefined")return;const legacy=JSON.parse(localStorage.getItem(LEGACY)||"[]")as QueuedRound[];for(const round of legacy)await queueRound(round);if(legacy.length)localStorage.removeItem(LEGACY)}
async function queueRoundInternal(round:QueuedRound){const now=new Date().toISOString();const existing=(await readQueue()).find(item=>item.id===round.id);if(existing)return;const sb=getSupabaseBrowserClient();const response=sb?await sb.auth.getUser():{data:{user:null}};await put({id:round.id,kind:"round",payload:round,status:"pending",attempts:0,created_at:now,updated_at:now,next_attempt_at:null,last_error:null,user_id:response.data.user?.id||null});if("serviceWorker"in navigator&&"SyncManager"in window)try{const registration=await navigator.serviceWorker.ready;await(registration as ServiceWorkerRegistration&{sync:{register:(tag:string)=>Promise<void>}}).sync.register("vector-golf-sync")}catch{}}
export function queueRound(round:QueuedRound){pendingWrites=pendingWrites.then(()=>queueRoundInternal(round));return pendingWrites}
export async function deleteQueuedItem(id:string){await remove(id)}
export async function retryQueuedItem(id:string){const item=(await readQueue()).find(record=>record.id===id);if(!item)return;await put({...item,status:"pending",next_attempt_at:null,last_error:null,updated_at:new Date().toISOString()});return syncQueue(true)}
export async function syncQueue(force=false){await pendingWrites;if(syncing)return{synced:0,remaining:(await readQueue()).length,reason:"already-running"};syncing=true;let synced=0;try{const sb=getSupabaseBrowserClient();const queue=await readQueue();if(!sb)return{synced:0,remaining:queue.length,reason:"not-configured"};const{data:{user}}=await sb.auth.getUser();if(!user)return{synced:0,remaining:queue.length,reason:"not-signed-in"};if(typeof navigator!=="undefined"&&!navigator.onLine)return{synced:0,remaining:queue.length,reason:"offline"};for(const item of queue){if(item.user_id&&item.user_id!==user.id)continue;if(!force&&item.next_attempt_at&&new Date(item.next_attempt_at)>new Date())continue;const{error}=await sb.rpc("sync_round_payload",{payload:{...item.payload,player_id:user.id}});if(!error){await remove(item.id);synced++;continue}const attempts=item.attempts+1,delay=Math.min(30*60*1000,Math.pow(2,Math.min(attempts,8))*5000);await put({...item,status:attempts>=5?"failed":"pending",attempts,last_error:error.message,next_attempt_at:new Date(Date.now()+delay).toISOString(),updated_at:new Date().toISOString()})}return{synced,remaining:(await readQueue()).length,reason:null}}finally{syncing=false;changed()}}
export const syncQueuedRounds=()=>syncQueue();export const SYNC_EVENT=EVENT;
