export type TrackmanShotRow={id:string;session_id:string;source_row:number;club:string|null;ball_speed:number|null;club_speed:number|null;smash_factor:number|null;carry:number|null;total:number|null;launch_angle:number|null;launch_direction:number|null;spin_rate:number|null;spin_axis:number|null;height:number|null;landing_angle:number|null;curve:number|null;side_distance:number|null;face_angle:number|null;club_path:number|null;face_to_path:number|null;attack_angle:number|null;dynamic_loft:number|null;spin_loft:number|null;low_point:number|null;swing_plane:number|null;swing_direction:number|null;impact_height:number|null;impact_offset:number|null};
export type MetricKey=keyof TrackmanShotRow;
export type MetricSummary={key:MetricKey;label:string;unit:string;count:number;mean:number|null;sd:number|null;min:number|null;max:number|null;cv:number|null};
export const metricDefinitions:{key:MetricKey;label:string;unit:string;group:string}[]=[
 {key:"ball_speed",label:"Ball speed",unit:"mph",group:"Ball"},{key:"carry",label:"Carry",unit:"yd",group:"Ball"},{key:"total",label:"Total",unit:"yd",group:"Ball"},{key:"launch_angle",label:"Launch",unit:"°",group:"Ball"},{key:"launch_direction",label:"Launch direction",unit:"°",group:"Ball"},{key:"spin_rate",label:"Spin",unit:"rpm",group:"Ball"},{key:"spin_axis",label:"Spin axis",unit:"°",group:"Ball"},{key:"height",label:"Peak height",unit:"ft",group:"Ball"},{key:"landing_angle",label:"Landing angle",unit:"°",group:"Ball"},{key:"side_distance",label:"Offline",unit:"yd",group:"Dispersion"},
 {key:"club_speed",label:"Club speed",unit:"mph",group:"Delivery"},{key:"smash_factor",label:"Smash",unit:"",group:"Delivery"},{key:"face_angle",label:"Face angle",unit:"°",group:"Delivery"},{key:"club_path",label:"Club path",unit:"°",group:"Delivery"},{key:"face_to_path",label:"Face to path",unit:"°",group:"Delivery"},{key:"attack_angle",label:"Attack angle",unit:"°",group:"Delivery"},{key:"dynamic_loft",label:"Dynamic loft",unit:"°",group:"Delivery"},{key:"spin_loft",label:"Spin loft",unit:"°",group:"Delivery"},{key:"low_point",label:"Low point",unit:"in",group:"Delivery"},{key:"swing_plane",label:"Swing plane",unit:"°",group:"Delivery"},{key:"swing_direction",label:"Swing direction",unit:"°",group:"Delivery"},
 {key:"impact_offset",label:"Impact heel/toe",unit:"mm",group:"Impact"},{key:"impact_height",label:"Impact high/low",unit:"mm",group:"Impact"}
];
const round=(value:number)=>Math.round(value*10)/10;
export function summarise(shots:TrackmanShotRow[],definition=metricDefinitions):MetricSummary[]{return definition.map(item=>{const values=shots.map(shot=>shot[item.key]).filter((value):value is number=>typeof value==="number"&&Number.isFinite(value));if(!values.length)return{...item,count:0,mean:null,sd:null,min:null,max:null,cv:null};const mean=values.reduce((a,b)=>a+b,0)/values.length;const variance=values.length>1?values.reduce((total,value)=>total+(value-mean)**2,0)/(values.length-1):0;const sd=Math.sqrt(variance);return{...item,count:values.length,mean:round(mean),sd:round(sd),min:round(Math.min(...values)),max:round(Math.max(...values)),cv:mean?round(Math.abs(sd/mean)*100):null};});}
export function evidenceFlags(shots:TrackmanShotRow[],summaries:MetricSummary[]){if(shots.length<5)return[{level:"insufficient",title:"More shots required",detail:`${shots.length} shots selected. Use at least five comparable shots before treating a pattern as evidence.`}];const get=(key:MetricKey)=>summaries.find(item=>item.key===key);const flags:{level:string;title:string;detail:string}[]=[];const offline=get("side_distance"),carry=get("carry"),facePath=get("face_to_path"),strikeX=get("impact_offset"),strikeY=get("impact_height");if(offline?.sd!=null)flags.push({level:offline.sd>10?"attention":"stable",title:offline.sd>10?"Wide lateral dispersion":"Lateral dispersion controlled",detail:`Offline standard deviation is ${offline.sd} ${offline.unit}. This describes the result pattern; it does not identify the swing cause.`});if(carry?.cv!=null)flags.push({level:carry.cv>5?"attention":"stable",title:carry.cv>5?"Carry consistency opportunity":"Carry consistency stable",detail:`Carry variation is ${carry.cv}% around the selected-shot mean.`});if(facePath?.sd!=null)flags.push({level:facePath.sd>2?"attention":"stable",title:facePath.sd>2?"Face-to-path delivery varies":"Face-to-path delivery stable",detail:`Face-to-path standard deviation is ${facePath.sd}°. Confirm strike and task constraints before diagnosing why.`});if(strikeX?.count||strikeY?.count)flags.push({level:"observed",title:"Impact data available",detail:`Impact location is populated for ${Math.max(strikeX?.count||0,strikeY?.count||0)} of ${shots.length} selected shots.`});else flags.push({level:"observed",title:"Impact tile not supplied",detail:"No impact-location values are available in this selection; no strike conclusion has been inferred."});return flags;}
export function comparison(current:TrackmanShotRow[],reference:TrackmanShotRow[]){const a=summarise(current),b=summarise(reference);return a.map(item=>{const prior=b.find(entry=>entry.key===item.key);return{...item,reference:prior?.mean??null,change:item.mean!=null&&prior?.mean!=null?round(item.mean-prior.mean):null};}).filter(item=>item.mean!=null||item.reference!=null);}
