"use client";
/* eslint-disable @typescript-eslint/no-unused-vars */
import {useCallback,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {AppShell} from "../../ui/app-shell";
import {getSupabaseBrowserClient} from "../../../lib/supabase/client";
import {usePlayerData} from "../../../lib/use-player-data";
import {comparison,evidenceFlags,metricDefinitions,summarise,type TrackmanShotRow} from "../../../lib/trackman-analysis";
import "../../trackman-analysis.css";
type Player={id:string;display_name:string|null;email:string};
type Session={id:string;title:string;session_date:string|null;test_type:"standard"|"baseline"|"no_aid"|"transfer"|"retest";comparison_group:string|null;trackman_shots:TrackmanShotRow[]};
const shotFields="id,session_id,source_row,club,ball_speed,club_speed,smash_factor,carry,total,launch_angle,launch_direction,spin_rate,spin_axis,height,landing_angle,curve,side_distance,face_angle,club_path,face_to_path,attack_angle,dynamic_loft,spin_loft,low_point,swing_plane,swing_direction,impact_height,impact_offset";
const types=["standard","baseline","no_aid","transfer","retest"] as const;
function value(input:number|null|undefined,digits=1){return input==null?"—":input.toFixed(digits)}
export default function TrackmanAnalysis(){const{profile}=usePlayerData();const canCoach=profile?.role==="coach"||profile?.role==="admin";const[players,setPlayers]=useState<Player[]>([]);const[playerId,setPlayerId]=useState("");const[sessions,setSessions]=useState<Session[]>([]);const[sessionId,setSessionId]=useState("");const[referenceId,setReferenceId]=useState("");const[club,setClub]=useState("all");const[group,setGroup]=useState("Ball");const[message,setMessage]=useState("");
 const loadPlayers=useCallback(async()=>{const sb=getSupabaseBrowserClient();if(!sb||!profile||!canCoach)return;const{data:links}=await sb.from("coach_player_links").select("player_id").eq("coach_id",profile.id);const ids=(links||[]).map(item=>item.player_id);if(!ids.length)return;const{data}=await sb.from("profiles").select("id,display_name,email").in("id",ids).order("display_name");const rows=(data||[])as Player[];setPlayers(rows);setPlayerId(current=>current||rows[0]?.id||"");},[profile,canCoach]);
 const loadSessions=useCallback(async()=>{const sb=getSupabaseBrowserClient();if(!sb||!playerId)return;const{data,error}=await sb.from("trackman_sessions").select(`id,title,session_date,test_type,comparison_group,trackman_shots(${shotFields})`).eq("player_id",playerId).order("session_date",{ascending:false,nullsFirst:false});if(error){setMessage(error.message);return;}const rows=(data||[])as unknown as Session[];setSessions(rows);setSessionId(current=>rows.some(item=>item.id===current)?current:rows[0]?.id||"");},[playerId]);
 useEffect(()=>{const timer=setTimeout(()=>void loadPlayers(),0);return()=>clearTimeout(timer);},[loadPlayers]);useEffect(()=>{const timer=setTimeout(()=>void loadSessions(),0);return()=>clearTimeout(timer);},[loadSessions]);
 const selected=sessions.find(item=>item.id===sessionId);const reference=sessions.find(item=>item.id===referenceId);const clubs=useMemo(()=>Array.from(new Set((selected?.trackman_shots||[]).map(shot=>shot.club).filter(Boolean)as string[])).sort(),[selected]);const shots=useMemo(()=>club==="all"?(selected?.trackman_shots||[]):(selected?.trackman_shots||[]).filter(shot=>shot.club===club),[selected,club]);const referenceShots=useMemo(()=>club==="all"?(reference?.trackman_shots||[]):(reference?.trackman_shots||[]).filter(shot=>shot.club===club),[reference,club]);const summaries=useMemo(()=>summarise(shots),[shots]);const flags=useMemo(()=>evidenceFlags(shots,summaries),[shots,summaries]);const comparisons=useMemo(()=>comparison(shots,referenceShots),[shots,referenceShots]);const visible=summaries.filter(item=>metricDefinitions.find(def=>def.key===item.key)?.group===group);const dispersion=shots.filter(shot=>shot.side_distance!=null&&shot.carry!=null);const maxCarry=Math.max(1,...dispersion.map(shot=>shot.carry||0));const maxSide=Math.max(10,...dispersion.map(shot=>Math.abs(shot.side_distance||0)))*1.2;
 const classify=async(type:typeof types[number])=>{const sb=getSupabaseBrowserClient();if(!sb||!selected)return;const{error}=await sb.rpc("classify_trackman_session",{target_session:selected.id,new_test_type:type,new_comparison_group:selected.comparison_group||""});setMessage(error?error.message:`Session marked ${type.replace("_"," ")}.`);if(!error)await loadSessions();};
 if(profile&&!canCoach)return <AppShell active="trackman"><div className="empty-state"><h2>Coach access required</h2><p>TrackMan analysis is available inside the coach workspace.</p></div></AppShell>;
 return <AppShell active="trackman"><header className="page-heading"><div><p className="eyebrow">Package 7G.2 · Session analysis</p><h1>See the pattern. Test the cause.</h1><p>Compare ball flight, delivery, strike and dispersion while keeping measured evidence separate from diagnosis.</p></div><Link className="secondary-action" href="/trackman">Import CSV</Link></header>{message&&<div className="success-banner">{message}</div>}
 <section className="tm-analysis-controls"><label>Player<select value={playerId} onChange={event=>{setPlayerId(event.target.value);setReferenceId("");}}>{players.map(player=><option value={player.id} key={player.id}>{player.display_name||player.email}</option>)}</select></label><label>Session<select value={sessionId} onChange={event=>{setSessionId(event.target.value);setClub("all");}}>{sessions.map(item=><option value={item.id} key={item.id}>{item.session_date||"No date"} · {item.title}</option>)}</select></label><label>Club<select value={club} onChange={event=>setClub(event.target.value)}><option value="all">All clubs</option>{clubs.map(item=><option key={item}>{item}</option>)}</select></label><label>Compare with<select value={referenceId} onChange={event=>setReferenceId(event.target.value)}><option value="">No comparison</option>{sessions.filter(item=>item.id!==sessionId).map(item=><option value={item.id} key={item.id}>{item.test_type.replace("_"," ")} · {item.title}</option>)}</select></label></section>
 {!selected?<div className="empty-state"><h2>No TrackMan sessions yet</h2><p>Import a CSV and assign it to this player before opening analysis.</p></div>:<><section className="tm-session-strip"><div><span>Selected evidence</span><strong>{shots.length} shots</strong></div><div><span>Session type</span><strong>{selected.test_type.replace("_"," ")}</strong></div><div className="type-buttons">{types.map(type=><button className={selected.test_type===type?"active":""} onClick={()=>classify(type)} key={type}>{type.replace("_"," ")}</button>)}</div></section>
 <div className="tm-analysis-grid"><section className="tm-analysis-panel"><div className="section-heading"><div><p className="eyebrow">Dispersion</p><h2>Carry and lateral pattern</h2></div></div>{dispersion.length?<svg className="dispersion-chart" viewBox="0 0 600 360" role="img" aria-label="TrackMan shot dispersion"><line x1="300" x2="300" y1="25" y2="335"/><line x1="35" x2="565" y1="335" y2="335"/>{dispersion.map((shot,index)=>{const x=300+((shot.side_distance||0)/maxSide)*245;const y=335-((shot.carry||0)/maxCarry)*285;return <circle key={shot.id} cx={x} cy={y} r="6"><title>{`${shot.club||"Club"}: ${value(shot.carry)} yd, ${value(shot.side_distance)} yd offline`}</title></circle>})}<text x="40" y="353">Left</text><text x="535" y="353">Right</text><text x="307" y="35">{Math.round(maxCarry)} yd</text></svg>:<p className="empty-copy">Carry and offline columns are required for the dispersion view.</p>}</section>
 <section className="tm-analysis-panel"><div className="section-heading"><div><p className="eyebrow">Evidence flags</p><h2>What the sample supports</h2></div></div><div className="evidence-flag-list">{flags.map(flag=><article className={flag.level} key={flag.title}><strong>{flag.title}</strong><p>{flag.detail}</p></article>)}</div></section></div>
 <section className="tm-analysis-panel metric-workspace"><div className="metric-tabs">{["Ball","Delivery","Impact","Dispersion"].map(item=><button className={group===item?"active":""} onClick={()=>setGroup(item)} key={item}>{item}</button>)}</div><div className="metric-table header"><span>Parameter</span><span>Mean</span><span>SD</span><span>Range</span><span>Coverage</span></div>{visible.map(item=><div className="metric-table" key={String(item.key)}><strong>{item.label}</strong><span>{value(item.mean)} {item.unit}</span><span>{value(item.sd)} {item.unit}</span><span>{item.min==null?"—":`${item.min}–${item.max}`}</span><span>{item.count}/{shots.length}</span></div>)}</section>
 {reference&&<section className="tm-analysis-panel"><div className="section-heading"><div><p className="eyebrow">Like-for-like comparison</p><h2>{reference.title} → {selected.title}</h2></div></div><div className="comparison-grid">{comparisons.slice(0,16).map(item=><div key={String(item.key)}><span>{item.label}</span><strong>{value(item.mean)} {item.unit}</strong><small>{item.change==null?"No paired value":`${item.change>0?"+":""}${item.change} ${item.unit} vs reference`}</small></div>)}</div><p className="guardrail-copy">Changes describe these selected samples only. Confirm comparable club, task, environment and strike before attributing a cause.</p></section>}
 <section className="tm-analysis-panel shot-table-panel"><div className="section-heading"><div><p className="eyebrow">Shot evidence</p><h2>Shot-by-shot table</h2></div></div><div className="shot-table header"><span>#</span><span>Club</span><span>Ball</span><span>Carry</span><span>Launch</span><span>Spin</span><span>Face</span><span>Path</span><span>F→P</span><span>Attack</span><span>Offline</span></div>{shots.map(shot=><div className="shot-table" key={shot.id}><span>{shot.source_row}</span><strong>{shot.club||"—"}</strong><span>{value(shot.ball_speed)}</span><span>{value(shot.carry)}</span><span>{value(shot.launch_angle)}</span><span>{value(shot.spin_rate,0)}</span><span>{value(shot.face_angle)}</span><span>{value(shot.club_path)}</span><span>{value(shot.face_to_path)}</span><span>{value(shot.attack_angle)}</span><span>{value(shot.side_distance)}</span></div>)}</section></>}</AppShell>;
}
