-- Vector Golf Performance · Package 7E.2 evidence and recommendation engine
create table if not exists public.diagnostic_cases(id uuid primary key default gen_random_uuid(),player_id uuid not null references public.profiles(id) on delete cascade,shot_band text not null,status text not null default 'draft' check(status in('draft','approved','rejected','superseded')),confidence text not null check(confidence in('insufficient','emerging','moderate','strong')),confidence_score integer not null check(confidence_score between 0 and 100),priority_score numeric not null default 0,opportunities integer not null default 0,successes integer not null default 0,pattern_key text not null,observation text not null,interpretation text not null,evidence_summary text not null,next_test text not null,guardrail text not null,coach_note text,created_by uuid not null references public.profiles(id) on delete cascade,reviewed_by uuid references public.profiles(id) on delete set null,reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.case_recommendations(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.diagnostic_cases(id) on delete cascade,library_item_id uuid not null references public.library_items(id) on delete restrict,sequence integer not null default 1,recommendation_role text not null check(recommendation_role in('test','practice','physical_support')),rationale text not null,coach_selected boolean not null default true,created_at timestamptz not null default now(),unique(case_id,library_item_id));
create index if not exists diagnostic_cases_player_status_idx on public.diagnostic_cases(player_id,status,created_at desc);create index if not exists case_recommendations_case_idx on public.case_recommendations(case_id,sequence);
alter table public.diagnostic_cases enable row level security;alter table public.case_recommendations enable row level security;
drop policy if exists "players read approved cases" on public.diagnostic_cases;drop policy if exists "coaches read player cases" on public.diagnostic_cases;drop policy if exists "coaches create player cases" on public.diagnostic_cases;drop policy if exists "coaches update player cases" on public.diagnostic_cases;
create policy "players read approved cases" on public.diagnostic_cases for select using(player_id=auth.uid() and status='approved');create policy "coaches read player cases" on public.diagnostic_cases for select using(public.is_library_editor() and(player_id=auth.uid() or public.is_coach_of(player_id)));create policy "coaches create player cases" on public.diagnostic_cases for insert with check(public.is_library_editor() and created_by=auth.uid() and(player_id=auth.uid() or public.is_coach_of(player_id)));create policy "coaches update player cases" on public.diagnostic_cases for update using(public.is_library_editor() and(player_id=auth.uid() or public.is_coach_of(player_id))) with check(public.is_library_editor() and(player_id=auth.uid() or public.is_coach_of(player_id)));
drop policy if exists "users read visible recommendations" on public.case_recommendations;drop policy if exists "coaches manage recommendations" on public.case_recommendations;
create policy "users read visible recommendations" on public.case_recommendations for select using(exists(select 1 from public.diagnostic_cases c where c.id=case_id and((c.player_id=auth.uid() and c.status='approved')or(public.is_library_editor()and(c.player_id=auth.uid()or public.is_coach_of(c.player_id))))));create policy "coaches manage recommendations" on public.case_recommendations for all using(exists(select 1 from public.diagnostic_cases c where c.id=case_id and public.is_library_editor()and(c.player_id=auth.uid()or public.is_coach_of(c.player_id)))) with check(exists(select 1 from public.diagnostic_cases c where c.id=case_id and public.is_library_editor()and(c.player_id=auth.uid()or public.is_coach_of(c.player_id))));
grant select,insert,update on public.diagnostic_cases to authenticated;grant select,insert,update,delete on public.case_recommendations to authenticated;
