-- Vector Golf Performance · Package 7H.1 atomic, idempotent round synchronisation
create or replace function public.sync_round_payload(payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare round_id uuid:=(payload->>'id')::uuid;target_player uuid:=(payload->>'player_id')::uuid;band jsonb;shot jsonb;band_count integer:=0;shot_count integer:=0;
begin
 if auth.uid() is null or target_player<>auth.uid() then raise exception 'Round can only be synced by its player';end if;
 if exists(select 1 from rounds where sync_key=round_id and player_id<>target_player) then raise exception 'Synchronisation key belongs to another player';end if;
 insert into rounds(id,player_id,played_at,course_name,entry_mode,sync_key) values(round_id,target_player,(payload->>'recordedAt')::timestamptz,coalesce(nullif(payload->>'courseName',''),'Not recorded'),coalesce(nullif(payload->>'entryMode',''),'quick')::round_entry_mode,round_id) on conflict(sync_key) do update set played_at=excluded.played_at,course_name=excluded.course_name,entry_mode=excluded.entry_mode,updated_at=now();
 for band in select value from jsonb_array_elements(coalesce(payload->'bands','[]'::jsonb)) loop if band->>'opportunities' is not null then insert into shot_band_results(round_id,player_id,shot_band,opportunities,successes) values(round_id,target_player,band->>'label',(band->>'opportunities')::integer,nullif(band->>'successes','')::integer) on conflict(round_id,shot_band) do update set opportunities=excluded.opportunities,successes=excluded.successes;band_count:=band_count+1;end if;end loop;
 for shot in select value from jsonb_array_elements(coalesce(payload->'detailedShots','[]'::jsonb)) loop if exists(select 1 from detailed_shots where id=(shot->>'id')::uuid and player_id<>target_player) then raise exception 'Shot synchronisation key belongs to another player';end if;insert into detailed_shots(id,round_id,player_id,hole_number,shot_sequence,shot_band,success,miss_length,miss_direction) values((shot->>'id')::uuid,round_id,target_player,(shot->>'holeNumber')::integer,(shot->>'sequence')::integer,shot->>'shotBand',(shot->>'success')::boolean,nullif(shot->>'missLength',''),nullif(shot->>'missDirection','')) on conflict(id) do update set shot_band=excluded.shot_band,success=excluded.success,miss_length=excluded.miss_length,miss_direction=excluded.miss_direction;shot_count:=shot_count+1;end loop;
 return jsonb_build_object('status','synced','round_id',round_id,'bands',band_count,'shots',shot_count);
end $$;
grant execute on function public.sync_round_payload(jsonb) to authenticated;
