-- Vector Golf Performance · unified P-system movement aids and workout composition
create table if not exists public.swing_movements (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  p_position text not null check (p_position in ('P1','P2','P3','P4','P5','P6','P7','P8','P9','P10')),
  title text not null,
  body_target text not null,
  pressure_target text not null,
  hands_arms_target text not null,
  shaft_face_target text not null,
  incorrect_patterns text not null,
  rehearsal text not null,
  acceptance_gate text not null,
  applicable_categories text[] not null default array['full swing']::text[],
  status text not null default 'approved' check (status in ('draft','approved','retired')),
  source_reference text not null default 'Vector Unified P-System Swing Model Review',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.session_blocks
  add column if not exists swing_movement_id uuid references public.swing_movements(id) on delete set null,
  add column if not exists swing_movement_source text,
  add column if not exists swing_movement_rationale text;

do $$ begin
  alter table public.session_blocks add constraint session_blocks_swing_movement_source_check
    check (swing_movement_source is null or swing_movement_source in ('vector_engine','coach_override','player_override'));
exception when duplicate_object then null; end $$;

insert into public.swing_movements
  (code,p_position,title,body_target,pressure_target,hands_arms_target,shaft_face_target,incorrect_patterns,rehearsal,acceptance_gate)
values
('VSM-P1','P1','Athletic address','Pelvis and ribcage neutral to slightly flexed; lead shoulder modestly higher than trail; hips, knees and feet organised parallel to the intended start-line datum.','Approximately 55% lead-foot pressure for a stock 7-iron, balanced heel-to-forefoot with no forced sway.','Arms hang from the shoulder sockets; elbows soft and connected; hands beneath the chin with lead wrist close to flat and trail wrist softly extended.','Shaft inclines slightly toward target; face square to intended start line; sole sits without excessive toe-up or heel-up.','Excessive trail pressure, reaching for the ball, hands forced far forward, face preset open/closed, or ball position that moves low point away from the intended strike.','Build the address from the ground upward, pause, then make three slow starts while preserving balance and face aim.','Stable balance, centred strike rehearsal and clubface aligned within the coach-set start-line window.'),
('VSM-P2','P2','Organised takeaway','Chest and pelvis begin turning together without early pelvic thrust or lateral slide; inclination to the ground is retained.','Pressure begins moving into the trail foot while the centre of mass remains controlled inside the stance.','Lead arm stays connected to the chest; hands remain in front of the sternum rather than snatching inside or lifting outside.','Shaft approximately parallel to the ground and target line; clubhead outside the hands from down-the-line; face broadly matches spine inclination.','Rolling the face open, dragging the club inside, disconnecting the arms, or swaying the pelvis creates unreliable plane and face conditions.','Move from P1 to P2 in four seconds with an alignment stick outside the hands; freeze and check clubhead, hands and face.','Five consecutive rehearsals reach the same P2 window without loss of posture or balance.'),
('VSM-P3','P3','Width and depth','Thorax continues turning over a controlled pelvis; lead side remains long without losing forward inclination.','Trail-foot pressure is established without rolling onto the outside edge.','Lead arm approximately parallel to the ground, hands opposite the trail chest, trail elbow beginning to fold while staying in front of the seam line.','Shaft points broadly at or just inside the target line; face is neither fanned open nor excessively shut relative to lead forearm.','Collapsed width, excessive hand depth, vertical arm lift or forearm roll can force a compensating reroute.','Rehearse P2–P3 with a towel under the lead armpit and stop before the arms outrun the chest turn.','Hand depth, lead-arm angle and clubface repeat within the coach-marked video window.'),
('VSM-P4','P4','Structured top','Thorax completes its turn while pelvis retains depth; lead side stays inclined and the head remains inside the stance rather than swaying.','Pressure is predominantly trail foot, ready to recenter before the arms descend.','Lead arm crosses the shoulder line without excessive lift; trail elbow remains functionally in front of the torso; wrists are fully set without forced overswing.','Shaft direction is compatible with the intended delivery plane; face broadly matches lead-wrist condition rather than hanging open or severely bowed shut.','Reverse pivot, pelvis moving toward the ball, arm overrun, flying trail elbow and extreme wrist conditions make delivery timing dependent.','Make three-quarter backswings to a wall or visual checkpoint; hold P4, recenter pressure, then return to address.','Balanced hold with repeatable hand height, depth, lead-wrist and shaft direction.'),
('VSM-P5','P5','Recentered transition','Pelvis begins opening while retaining hip depth; thorax responds without spinning open ahead of the arms.','Pressure moves rapidly toward the lead foot before the club reaches P5; vertical force is not yet spent in an early jump.','Hands lower in front of the trail shoulder; trail elbow moves toward the ribcage while lead wrist retains its organised condition.','Shaft shallows modestly relative to the backswing without being tipped steep or trapped excessively behind; face remains matched to wrist conditions.','Upper-body lunge, early hip extension, steep shaft pitch, excessive shallowing or late pressure shift produces unstable path and contact.','From P4, pump to P5 three times while moving pressure leadward and keeping the trail hip back, then swing through at half speed.','Pressure is leadward and shaft/hand delivery repeats without the pelvis moving closer to the ball.'),
('VSM-P6','P6','Functional delivery','Pelvis is open, chest less open than pelvis, trail shoulder lower; pelvis retains depth and side bend develops without hanging back.','Most pressure is lead foot, with the lead leg accepting load and the trail heel beginning to unload naturally.','Hands are ahead of the trail thigh; trail elbow remains bent and in front of the hip; lead wrist is flat to slightly flexed and trail wrist extended.','Shaft approximately parallel to the ground, clubhead behind the hands but not excessively trapped; face is close to matching spine/lead-wrist organisation.','Early release, handle stall, steep or excessively under-plane shaft, open face, pelvis thrust and trail-foot hang-back alter path, face and strike.','Pump P5–P6 with an impact bag or delivery stick, then turn through without throwing the clubhead from the top.','Hands, shaft and face enter the coach-defined delivery corridor while pressure and pelvis depth remain functional.'),
('VSM-P7','P7','Stock 7-iron impact','Pelvis and thorax open to target, lead side extending and trail side bent; head remains behind the ball without the body hanging back.','Approximately 80–90% lead-foot pressure, with force directed through a stable lead leg.','Hands ahead of the ball; lead wrist flat to slightly flexed, trail wrist extended; arms retain enough structure to control radius.','Target window: face 0° to +1°, path +1° to +3°, face-to-path -2° to 0°, attack -3.5° to -5°, swing direction -1° to +1°, shaft lean +4° to +7°, dynamic lie 0° to +2° toe-up, strike within 8 mm of centre.','Open/closed face, out-to-in or excessive in-to-out delivery, low-point behind ball, loss of radius, early extension, handle stall and unsuitable dynamic lie cause the principal start-line, curve and contact faults.','Use waist-high impact rehearsals: pressure lead, handle forward, chest turning and strike ball then turf. Progress only when contact and start line stabilise.','Three of five shots meet the drill outcome plus coach-selected impact/strike windows; numerical windows are Vector teaching specifications, not universal laws.'),
('VSM-P8','P8','Connected exit','Chest continues opening and pelvis remains deep; lead side extends without backing away from the strike.','Pressure remains leadward as the trail foot rolls and releases rather than pushing the pelvis toward the ball.','Both arms lengthen after impact before folding naturally; hands exit around the body in response to rotation.','Shaft exits on a predictable inclination; face rotation is gradual and governed by body/arm motion, not a late hand flip.','Chicken-wing lead arm, stalled pivot, excessive hand roll, high handle or trapped exit can reflect an unstable impact pattern.','Hit half shots from P6 to P8, finishing with long arms and chest facing left of target while preserving balance.','Start line and strike remain stable while the P8 arm extension and exit repeat.'),
('VSM-P9','P9','Rotated follow-through','Torso is fully rotated, pelvis remains under the ribcage and spine is tall rather than collapsing backward.','Pressure is almost entirely lead foot; trail foot supports lightly on the toe.','Lead elbow folds after extension; trail arm extends; hands travel around the lead shoulder without forced manipulation.','Shaft and face decelerate as a consequence of the pivot; club exits consistently with the intended shot pattern.','Incomplete rotation, reverse-C collapse, abrupt arm braking or excessive face roll indicates compensations earlier in the motion.','Swing P3 to P9 at 60% speed and hold, checking chest rotation, tall lead side and quiet balance.','Hold P9 for three seconds with repeatable finish direction and no step or fall.'),
('VSM-P10','P10','Balanced finish','Body is tall and fully rotated with belt buckle and chest facing the target side; pelvis stacked under the torso.','Nearly all pressure is supported by the lead foot with the trail toe as a balance point.','Arms fold comfortably over the lead shoulder; elbows and wrists are relaxed after completion.','Shaft finishes around the body without forced wrapping; clubface position is an outcome, not a pose to manufacture.','Falling backward, stepping, unfinished rotation or excessive spinal extension often exposes speed, pressure or sequencing beyond current control.','Complete a full swing, hold the finish for five seconds, then score balance before looking at ball flight.','Five consecutive swings finish in balance and within the intended effort level.' )
on conflict (code) do update set
  p_position=excluded.p_position,title=excluded.title,body_target=excluded.body_target,
  pressure_target=excluded.pressure_target,hands_arms_target=excluded.hands_arms_target,
  shaft_face_target=excluded.shaft_face_target,incorrect_patterns=excluded.incorrect_patterns,
  rehearsal=excluded.rehearsal,acceptance_gate=excluded.acceptance_gate,status='approved',updated_at=now();

alter table public.swing_movements enable row level security;
drop policy if exists "authenticated read approved swing movements" on public.swing_movements;
create policy "authenticated read approved swing movements" on public.swing_movements
  for select to authenticated using (status='approved' or public.is_library_editor());
drop policy if exists "library editors manage swing movements" on public.swing_movements;
create policy "library editors manage swing movements" on public.swing_movements
  for all to authenticated using (public.is_library_editor()) with check (public.is_library_editor());
grant select,insert,update,delete on public.swing_movements to authenticated;
