-- Vector Golf Performance · Package 7F.3 player delivery, workload and feedback
create table if not exists public.session_logs(id uuid primary key default gen_random_uuid(),session_id uuid not null references public.programme_sessions(id) on delete cascade,player_id uuid not null references public.profiles(id) on delete cascade,readiness integer check(readiness between 1 and 5),energy integer check(energy between 1 and 5),soreness integer check(soreness between 1 and 5),stress integer check(stress between 1 and 5),pain_level integer not null default 0 check(pain_level between 0 and 10),pain_location text,state text check(state in('performing','stable','fatigued','declining')),safety_status text not null default 'clear' check(safety_status in('clear','monitor','stop_and_review')),completion_status text not null default 'not_started' check(completion_status in('not_started','partial','completed','stopped')),actual_minutes integer check(actual_minutes between 0 and 600),session_rpe integer check(session_rpe between 1 and 10),session_load integer generated always as(coalesce(actual_minutes,0)*coalesce(session_rpe,0)) stored,player_notes text,started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(session_id,player_id));
create table if not exists public.block_completions(id uuid primary key default gen_random_uuid(),session_log_id uuid not null references public.session_logs(id) on delete cascade,session_block_id uuid not null references public.session_blocks(id) on delete cascade,completed boolean not null default false,result_note text,completed_at timestamptz,unique(session_log_id,session_block_id));
create table if not exists public.session_reviews(id uuid primary key default gen_random_uuid(),session_log_id uuid not null unique references public.session_logs(id) on delete cascade,coach_id uuid not null references public.profiles(id) on delete cascade,decision text not null check(decision in('keep','progress','modify','stop')),feedback text not null,evidence_note text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists session_logs_player_idx on public.session_logs(player_id,completed_at desc);create index if not exists block_completions_log_idx on public.block_completions(session_log_id);
create or replace function public.set_session_response_state() returns trigger language plpgsql as $$ begin new.safety_status=case when new.pain_level>=5 then 'stop_and_review' when new.pain_level>0 or coalesce(new.readiness,3)<=2 then 'monitor' else 'clear' end;new.state=case when new.pain_level>=5 or(coalesce(new.readiness,3)<=2 and coalesce(new.energy,3)<=2)then 'declining' when coalesce(new.readiness,3)<=2 or coalesce(new.soreness,3)>=4 or coalesce(new.stress,3)>=4 then 'fatigued' when coalesce(new.readiness,3)>=4 and coalesce(new.energy,3)>=4 and coalesce(new.soreness,3)<=2 then 'performing' else 'stable' end;if new.pain_level>=5 then new.completion_status='stopped';end if;new.updated_at=now();return new;end;$$;
drop trigger if exists session_response_state_trigger on public.session_logs;create trigger session_response_state_trigger before insert or update on public.session_logs for each row execute procedure public.set_session_response_state();
create or replace function public.week_adherence(target_week uuid,target_player uuid) returns table(planned_minutes bigint,actual_minutes bigint,sessions_completed bigint,sessions_total bigint,adherence_percent numeric,session_load bigint) language sql stable security definer set search_path=public as $$ select coalesce((select sum(b.minutes) from public.programme_sessions s join public.session_blocks b on b.session_id=s.id where s.programme_week_id=target_week),0),coalesce(sum(l.actual_minutes),0),count(l.id) filter(where l.completion_status='completed'),(select count(*) from public.programme_sessions where programme_week_id=target_week),case when coalesce((select sum(b.minutes) from public.programme_sessions s join public.session_blocks b on b.session_id=s.id where s.programme_week_id=target_week),0)>0 then round(100.0*coalesce(sum(l.actual_minutes),0)/(select sum(b.minutes) from public.programme_sessions s join public.session_blocks b on b.session_id=s.id where s.programme_week_id=target_week),1) else 0 end,coalesce(sum(l.session_load),0) from public.programme_sessions s left join public.session_logs l on l.session_id=s.id and l.player_id=target_player where s.programme_week_id=target_week $$;
alter table public.session_logs enable row level security;alter table public.block_completions enable row level security;alter table public.session_reviews enable row level security;
create policy "players manage own released session logs" on public.session_logs for all using(player_id=auth.uid()) with check(player_id=auth.uid() and exists(select 1 from public.programme_sessions s join public.programme_weeks w on w.id=s.programme_week_id join public.programmes p on p.id=w.programme_id where s.id=session_id and p.player_id=auth.uid() and p.status in('published','completed') and w.status in('published','completed')));create policy "coaches read linked session logs" on public.session_logs for select using(public.is_coach_of(player_id));
create policy "players manage own block completion" on public.block_completions for all using(exists(select 1 from public.session_logs l where l.id=session_log_id and l.player_id=auth.uid())) with check(exists(select 1 from public.session_logs l where l.id=session_log_id and l.player_id=auth.uid()));create policy "coaches read linked block completion" on public.block_completions for select using(exists(select 1 from public.session_logs l where l.id=session_log_id and public.is_coach_of(l.player_id)));
create policy "players read own coach review" on public.session_reviews for select using(exists(select 1 from public.session_logs l where l.id=session_log_id and l.player_id=auth.uid()));create policy "coaches manage linked session review" on public.session_reviews for all using(coach_id=auth.uid() and exists(select 1 from public.session_logs l where l.id=session_log_id and public.is_coach_of(l.player_id))) with check(coach_id=auth.uid() and exists(select 1 from public.session_logs l where l.id=session_log_id and public.is_coach_of(l.player_id)));
grant select,insert,update,delete on public.session_logs,public.block_completions,public.session_reviews to authenticated;grant execute on function public.week_adherence(uuid,uuid) to authenticated;
